version: '2'
services:
  fusion-plugin-apollo:
    build: .
    volumes:
      - '.:/fusion-plugin-apollo'
      - /fusion-plugin-apollo/node_modules/
      - /fusion-plugin-apollo/dist/
      - /fusion-plugin-apollo/dist-tests/
  fusion-plugin-apollo-node-last:
    extends: fusion-plugin-apollo
    build:
      context: .
      args:
        BASE_IMAGE: 'uber/web-base-image:1.0.9'
